version: "2"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=regmondb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8000:80"
    links:
      - db
    volumes:
      # connect our local app folder with docker app folder
      - .:/var/www/public
      # vendor and node_modules folders already exists in docker image 
      # the previous command will overwrite docker app folder with local app folder
      # with this commands we tell docker to not override this folders
      - /var/www/public/vendor/
      - /var/www/public/node_modules/
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_DATABASE=regmondb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
      # set initial mysql install script
      # we not need this anymore because we install mysql schema with the config.php
      #- ./extra/_regmondb_init_v3.012.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    links:
      - db
    environment:
      MYSQL_USER: dbuser
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db

volumes:
  mysql_data:
    driver: local
