version: "2"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=regmondb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8000:80"
    links:
      - db
    volumes:
      - .:/var/www/public
      - /var/www/public/vendor/
      - /var/www/public/node_modules/
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_DATABASE=regmondb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./extra/_regmondb_init_v3.012_en.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    links:
      - db
    environment:
      MYSQL_USER: dbuser
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: db

volumes:
  mysql_data:
    driver: local
